### ISSUE TITLE
Setup MariaDB

### ISSUE THREAD

**Issue by timothyvanderaerden** [optimise-group/bifrost#102]
## Summary

After some discussions we are going to stick with MariaDB which is currently already used by Sippy.
This issue is going to migrate our config and setup to MariaDB. It's not as easy as just replacing `postgrex` with `myxql`.

There is already a `mariadb` branch which can be used as a starting point.

## Todo

- [ ] Change Ecto Adapters
- [ ] What are we going to do with UUID's?
- [ ] Can we still use JSON as is?
- [ ] Miscellaneous changes
