### ISSUE TITLE
Port current API

### ISSUE THREAD

**Issue by timothyvanderaerden** [optimise-group/bifrost#108]
## Summary

This is a Elixir port of the current Sippy API (v2), this makes the transitioning easier while we prepare Sippy v4. The goal is to provide an almost fully compatible API without changing the underlying structure, since there are going to be some small changes we bump this version to v3. This version is just a stepping stone to a complete rewrite of our current infrastructure.

## Features

These are the features that are going to be ported.

- [x] Pbx #120 
  - [x] Dispatchers #133 
- [x] Reseller #116 
- [x] Account #111 
  - [x] Login (Bearer token) #113 
  - [x] Roles (admin, reseller, customer, user) #113
  - [x] Setting #114 
  - [x] Firebase auth #141 
- [x]  Cdr #123 
- [x] Phonebook #128 
- [x] Media #129 
- [x] User #134 
  - [x] location 3361c74a
  - [x] line keys #137 
- [x] MOH #130 
- [x] Codecs #132 
- [x] Extensions #134 
- [x] Rules #138 
- [x] Group #142 
- [x] Timetable #148 
  - [x] Holiday #148 
- [x] Inbound routes #139 
- [x] Provisioning #136 
  - [x] Device #131
  - [x] Flex desk #136 
    - [x] Flex desk log #150 
- [x] IVR #152 
- [x] Queue #151 
  - [x] Queue log #151 
- [x] Voicemail #140 
- [x] Custom destination #145 
- [x] Outbound rule #146 
- [x] Phone numbers #122 
- [ ] Integration #159 
  - Teamleader
- [x] Delete check (images, sound) #153 
  - Custom destination (needs: rules)
  - Group (needs: rules)
  - IVR (needs: rules)
  - Image (needs: pbx, sippeer)
  - Sound (needs: queues, ivrs, voicemail, rules)
  - Queue (needs: rules)
  - Sippeer/User (needs: rules, queue member, group member)
  - Timetables (needs: rules)
  - Voicemail (needs: rules)

## Todo

These are some general todo's that probably are linked to routes and features but can't be implemented because the may relay on features that aren't implemented yet.

- [x] Add Plug to check access to PBX
- [x] Check account management, reseller can manage accounts that he owns (PBX based), customers can only manage their own)
- [x] A user shouldn't be able to create accounts with higher access levels
- [x] Add `count` to JSON lists
- [x] Allow BLF label to be empty so it uses the name of the user :gift: optimise-group/provisioning#2
- [x] Allow resellers to create PBXes :gift: 
- [x] Add `pbxCount` to `resellers` JSON
- ~~Test accountcode/useralias generator~~
- ~~Test failed cc_card insertion~~
- [x] Get available numbers from PBX (`/:context/numbers/available`)
- [x] Set default sorting like v2
- [x] Ensure limit on queries can't exceed 50 (for CDR the date can't exceed a month)
- [x] Don't define default optional arguments twice (context, controller)
-  ~~Send SIP Notify when deleting phonebook (to sippeers with specified phonebook)~~
- [x] Implement PubSub #155 
  - Outbound rule
  - User cache/release
- [x] Add `click2dial` for users 8c2f7cbd
- [x] Increase line key value length

## Changes

There are some global changes on how the API behaves, it is however necessary to keep this to a minimum so we keep compatibility.

- "Already in use" errors now return a HTTP 422 instead of 400 status.
- The error object that is returned is now a changeset.
- Creating, updating and deleting an object return that object. This means the 201 HTTP-status code is replaced with 200.
- POST returns the object with ID and possible other generated values.

## Dropped features

These features are going to be dropped or changed.

- Provider
- Account "user" role (this role is currently not really used since it's too restrictive)
- Reseller billing
