### ISSUE TITLE
[Messaging] Implementation

### ISSUE THREAD

**Issue by timothyvanderaerden** [optimise-group/bifrost#85]
## Summary

This issue introduces the concept of messaging. Messaging should be possible between users within the same organization, however we should be able to introduce a way to couple messaging between organizations. Maybe we can to this through a link (or qr-code). This is something to tinker about.

I think the best way to go about this is to create "rooms", a room can be private which is basically direct messaging between two users, or a room can have multiple users (from the same organization). Then later on it should be possible to "connect" two rooms from different organizations together. Furthermore it should be possible to add endpoints, these endpoints can be SIP accounts. If a message is send it should also be transported with SIP to the endpoint, obviously the SIP endpoint should support it. We can detect it but that's something for another issue. Maybe we should only have endpoints as members of a room and link an endpoint to a user? Again, something to tinker about.

## Todo

- [ ] Messaging DB structure
- [ ] Messaging GraphQL implementation
- [ ] Endpoint/user presence (probably tracked in another issue)
- [ ] Messaging implementation over WS (absinthe subscriptions)
- [ ] Messaging implementation over SIP
- [ ] Connect rooms between organizations (maybe not this release)
